import { CaskAttributes } from '../../server/types/models'

export const marchCasks: CaskAttributes[] = [
  {
    name: 'Memories of days gone by',
    caskNumber: '82.28',
    price: '110',
    flavourProfile: 'Spicy & Sweet',
    age: '9',
    date: 'March 2011',
    region: 'Highland Eastern',
    caskType: 'Second-fill barrel',
    abv: '62.5',
    bottleOutturn: '221',
    allocation: '90',
    description: 'The aroma reminded one panellist initially of standing in front of the whole class writing a mathematical equation with chalk on a blackboard (the good old days!), while most of us got a basket of fruit full of  lychees, mandarins as well as strawberries and pineapple junks. Oozing with sweetness and tropical goodness on the palate neat but be aware, at the same time a fiery gingery heat. Nothing a drop of water cannot solve as the scent of fresh oak, vanilla biscuits and candy floss was followed by the very moreish taste of Scotch pancakes served with mixed berries and custard.'
  },
  {
    name: 'A complex character',
    caskNumber: '41.139',
    price: '115',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '12',
    date: 'April 2008',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '60.9',
    bottleOutturn: '190',
    allocation: '60',
    description: 'The complex nose held juicy pineapple and watermelon; vanilla fudge and puff candy; then thyme and sage in a potting shed. The palate’s main thrust delivered honey, Danish pastries, mango pudding with custard, Starburst and Skittles – the finish had clean oak, lemon peel and white pepper. The reduced nose returned to a fruity dimension – stewed apples, ripe pears and lime flavoured fondant sweets – other comments included wildflowers, rosewater, gorse and hawthorn; candied angelica on sponge cake and vending machine gumballs. The palate tasted older than the stated age – juniper, limoncello, gewürztraminer and perfumed cigarettes; spearmint Softmints, oak and vanilla.'
  },
  {
    name: 'Members remember embers',
    caskNumber: '93.151',
    price: '130',
    flavourProfile: 'Lightly Peated',
    age: '10',
    date: 'March 2010',
    region: 'Campbeltown',
    caskType: 'First-fill barrel',
    abv: '60.4',
    bottleOutturn: '212',
    allocation: '120',
    description: 'The nose had gentle smoke and earthy sweetness; sliced cooking apples, honeydew melon and homemade blackcurrant wine, caraway seeds, first aid kits and Elastoplast. The palate conveyed similar themes – eucalyptus leaves and lavender sprigs chucked on peat embers, the wisping smoke clung to our tweed jackets as we stood awaiting breakfast kippers with redcurrant jelly. The reduced nose got brown sauce on sausage rolls, dressed crab and Cajun fries; sweet smoke, eucalyptus-infused sauna wood and Kendal mint cake. The palate now encompassed sea spray, mussels cooked in white wine, coal sacks and herbal smoke, with cardamom, clove and ginger warming the finish.'
  },
  {
    name: 'Gripping fresh fruitiness',
    caskNumber: '35.281',
    price: '140',
    flavourProfile: 'Spicy & dry',
    age: '14',
    date: 'January 2006',
    region: 'Speyside Lossie',
    caskType: 'Refill hogshead',
    abv: '58.0',
    bottleOutturn: '296',
    allocation: '90',
    description: 'A minty, chalky freshness greeted the Panel before golden-coloured dried jumbo raisins, as well as sliced melon, served with a sprinkling of ginger appeared.  On the palate neat cracked black pepper crispy flatbread with salty butter and quince jelly before the sweeter taste of flapjacks, apple crumble and a maraschino cherry on a bamboo cocktail stick took centre stage. After a drop of water, we prepared a hot, sweet malted milk drink and toasted semolina pudding with pine nuts and cinnamon before we bit into a crisp Granny Smith apple, typically acidic but with that slight sweetness as occurring during storage. Fresh, fruity, sweet and a dry finish - gripping!'
  },
  {
    name: 'Is this the way to Amarillo?',
    caskNumber: '12.49',
    price: '115',
    flavourProfile: 'Spicy & sweet',
    age: '10',
    date: 'March 2010',
    region: 'Speyside Lossie',
    caskType: 'Second-fill IPA barrel',
    abv: '60.0',
    bottleOutturn: '235',
    allocation: '102',
    description: 'A cosy blanket of wool wrapped around bitter lemon, black grapes and tangerines as dried chamomile petals mixed with dark chocolate and lots of vanilla. Then on the palette came a burst of orange fruit from funky Amarillo hops that morphed into lime zest while dark chocolate remained with cinnamon, ginger and mace spice. A dash of water heralded an explosion of citrus fruit cascading over lemon drizzle cake in a pine forest. Earthy notes of herb gardens mirrored dried hops with bitter marmalade as the flavours now veered us towards bananas on burnt toast with cinnamon and persistent chocolate. After spending nine years in an ex-bourbon barrel this was transferred to an ex-Tempest Old Fashioned IPA cask for the remainder of its maturation.'
  },
  {
    name: 'Royal nonsense?',
    caskNumber: '72.97',
    price: '90',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '8',
    date: 'April 2012',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '62.3',
    bottleOutturn: '225',
    allocation: '72',
    description: 'On the nose neat we imagined traditional Austrian flower boxes displaying a variety of flowers like begonias, fuchsias, honeysuckle and foxgloves, mounted onto a wooden balcony. On the palate we stayed on that Austrian balcony and had a glass of white wine called Grüner Veltliner - vibrant, zesty with a dry minerality and a hint of pepper. Water released the sweet herbal notes of basil and thyme as well as green grape skins before the sweet perfumed scent of jasmine and rose water appeared. The taste a real ‘Kaiserschmarrn’ (named after the favourite dish of Austrian Emperor Franz Josef I) – light and fluffy shredded pancakes with raisins soaked in rum and served with plum compote.'
  },
  {
    name: 'The beast from the yeast',
    caskNumber: '53.355',
    price: '130',
    flavourProfile: 'Peated',
    age: '10',
    date: 'November 2009',
    region: 'Islay',
    caskType: 'Refill hogshead',
    abv: '56.2',
    bottleOutturn: '313',
    allocation: '120',
    description: "The brilliance of white, hot peat coals, a blizzard of hot smoked fish and then squid ink, oyster sauce, singed hessian cloth and molten marmite smoothies. A heady brew of cow fields and gusts of pin-sharp, slicing, petrol-driven minerality. With water, the salty teardrops flow. Briny, tartly citric, hyper-fresh coastal aspects and things like soggy kelp, rock pools and the sharpness of flint smoke. The mouth is huge, pristinely composed and showing all manner of chiselled minerals, crushed seashells, wind-lashed rigging, zingy fisherman's friends and carbolic sourdough. With water, there's smoky wort, peppered mackerel, juniper, mustard powder and a tempestuous collision of pure peat smoke, furious wash foam, jazzy salinity, Bonjela, mouthwash, gauze, tide-dashed seaweed and a fisherman's welly brimming with soda bread, eucalyptus toothpaste and bath salts."
  },
  {
    name: 'Granny’s kitchen on baking day',
    caskNumber: '9.191',
    price: '175',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '17',
    date: 'September 2003',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '55.4',
    bottleOutturn: '178',
    allocation: '90',
    description: "A comforting dram that ushered us into Granny’s kitchen on baking day – chopped hazelnuts, chocolate, orange, treacle scones and banana bread, honeyed tea cakes and a drop of vanilla essence into the bubbling tablet pot. The palate was richly honeyed, with initial silky smoothness and then a pleasing prickle effect towards the finish with tart nectarines, ginger loaf and cloves. The reduced nose had fragrant pink peppercorns and pressed flowers, glacé cherries, brown sugar, vanilla ice-cream and gradually more and more citrus. The palate developed rounded, mouth-coating loveliness and buttery goodness, with enticing tropical fruits (quince jelly, apricot Danish, dried papaya, peach cobbler)."
  },
  {
    name: 'Scotch goes West (Indies)',
    caskNumber: '112.69',
    price: '125',
    flavourProfile: 'Spicy & sweet',
    age: '14',
    date: 'August 2005',
    region: 'Highland Southern',
    caskType: 'Refill Jamaican rum barrel',
    abv: '58.8',
    bottleOutturn: '254',
    allocation: '90',
    description: "This sample cannot hide its past; lots of bubbling brown sugar, ginger nut biscuits, spiced banana chocolate muffins, honey-glazed grilled pineapple rings and the sweep of linseed oil on a new cricket bat. On the palate ‘feeling Hot-Hot- Hot’! But at the same time a spicy sweetness that we just could not resist – can you pick up the good vibes?  When we added water, plenty of ripe fruits like melon, grapefruit, papaya and carambola appeared next to a fig ginger jam. To taste; jerk chicken served with a peach and plum sauce. After 12 years in an ex-bourbon barrel we transferred this whisky into a refill barrel which previously matured rum from Jamaica."
  },
  {
    name: 'Bonbons',
    caskNumber: 'G10.30',
    price: '115',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '15',
    date: 'July 2005',
    region: 'Lowland',
    caskType: 'First-fill barrel',
    abv: '61.7',
    bottleOutturn: '200',
    allocation: '120',
    description: "Such an inviting nose of toasted coconut, pine sap, banana chips, brown sugar and beeswax on freshly carved wood. Enough said let’s have a try – vibrant and zesty, sweet and spicy; marzipan croissants with a peppered chocolate hazelnut spread, mango slices, whipped cream and olive oil cake. When we added water we walked through a pine forest after a rain shower, the smell is called geosmin, musky, cool and fresh yet at the same time an earthy-sweet aroma. On the palate a fresh-baked fruit pie in the hold of a wooden ship with a dash of herbal and white pepper – a real joy!"
  },
];

export const marchMidMonthCasks: CaskAttributes[] = [
  {
    name: 'Spring meadow picnic',
    caskNumber: '80.15',
    price: '115',
    flavourProfile: 'Spicy & Sweet',
    age: '12',
    date: 'March 2008',
    region: 'Speyside Spey',
    caskType: 'Refill hogshead',
    abv: '57.9',
    bottleOutturn: '276',
    allocation: '54',
    description: 'A fresh, youthful nose – we imagined children scampering around a springtime meadow with a picnic – daisy chains, sherbet lemons, Refreshers, mint crumbles, green apples, Madeira cake, rhubarb crumble and custard – all nicely anchored by hints of almonds, dunnage, pine and white pepper. The palate was a good cop, bad cop routine – sweet up front, with blossom honey and vanilla custard slice – then a spice wallop of stem ginger, liquorice root and black tea (including the wooden tea-chest). With water, the nose seemed drier (dried grass, cinnamon, leather, walnuts and wood), while the palate acquired more fruit – rhubarb rock, Clementine, pear, pineapple and mango.'
  },
  {
    name: 'Cooking on a rusty grill',
    caskNumber: '16.46',
    price: '90',
    flavourProfile: 'Peated',
    age: '6',
    date: 'July 2013',
    region: 'Highland Southern',
    caskType: 'Re-charred hogshead',
    abv: '64.9',
    bottleOutturn: '253',
    allocation: '84',
    description: 'A pungent, burnt and slightly medicinal note combined with a deep, dark and visceral smoke made this quite an experience to nose neat. That theme was carried on almost seamlessly on the palate. Hot, smoky, fierce and fiery but this was only one part of the story as there was also a creamy, syrupy mouthfeel with a fragrant, sweet and nutty flavour like a freshly brewed astragalus root tea. After dilution we barbequed meat on rusty grill grates as we eventually all sat down for a delicious meal of barbeque brisket seasoned with malt vinegar, Dijon mustard and Tabasco sauce – Texan style!'
  },
  {
    name: 'Riveting',
    caskNumber: '68.47',
    price: '120',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '11',
    date: 'October 2008',
    region: 'Highland Southern',
    caskType: 'First-fill Oloroso hogshead',
    abv: '55.4',
    bottleOutturn: '293',
    allocation: '90',
    description: 'A lovely deep fruity aroma like that of a raspberry pudding topped with roasted pecans, hazelnuts and warm vanilla sauce. The taste was delicious creamy – a chocolate mouse or a rose, raspberry and coconut fool of crystallized rose petals, double cream and toasted coconut flakes. Diluted we made a black currant crumble spicing it up with Aleppo pepper and a shot of a digestive bitter made from a variety of aromatic herbs and matured in Slovenian oak barrels. On the palate now dark chocolate truffles, marzipan and a finish of sweet dried figs. After nine years in an ex-bourbon hogshead, we transferred this whisky into a 1st fill Oloroso hogshead.'
  },
  {
    name: 'Irresistibly tropical',
    caskNumber: '37.132',
    price: '190',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '18',
    date: 'June 2002',
    region: 'Speyside Spey',
    caskType: 'First-fill Pedro Ximenez hogshead',
    abv: '57.1',
    bottleOutturn: '223',
    allocation: '78',
    description: 'The initial aroma of glue, nail polish and varnished wood soon turned into a rich sweetness of bramble jam, golden syrup and spiced vanilla custard. The taste neat had the sticky sweetness of black treacle and a dark chocolate marzipan bar with ginger. Water added a yummy rummy Jamaica cake as well as Grand Marnier deep-fried banana fritters and on the palate, we now smoked a sweet cigar from Trinidad; dark honey caramel sweetness, earth, coffee and delicate hints of vanilla-chestnut jam and caramelised fig syrup. After sixteen years in an ex-bourbon hogshead, we transferred this whisky into a 1st fill PX Sherry hogshead.'
  },
  {
    name: 'The tuck shop',
    caskNumber: '1.234',
    price: '120',
    flavourProfile: 'Spicy & sweet',
    age: '9',
    date: 'April 2011',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '58.4',
    bottleOutturn: '218',
    allocation: '96',
    description: 'A big bag of boiled sweets, mint humbugs, Moffat toffees, Campinos, vanilla sponge cake and expensive marzipan. Also, elegantly oily, nutty and with some wonderfully sweet notes of glazed pineapple. Reduction brought out deeper notes of kirsch dark chocolates, tonka bean ice cream and white jellybeans. Some fresh summer herbs and watermelon bring vivacity and breezy freshness.  The palate opened with a touch of spice then runny honey over fresh strawberries, banana bread, marmalade with coriander seed and mango pudding with a lick of beeswax. With water we found gloopy fruit salad juices, fatty coconut milk, buttery crumpets, crumbly scones with rhubarb jam and stem ginger in syrup. Some liquorice, paper and tobacco adding stout weightiness in the background.'
  },
  {
    name: 'Not just coastal',
    caskNumber: '93.144',
    price: '185',
    flavourProfile: 'Lightly peated',
    age: '17',
    date: 'May 2002',
    region: 'Campbeltown',
    caskType: 'Second-fill barrel',
    abv: '56.3',
    bottleOutturn: '199',
    allocation: '60',
    description: 'A rich profusion of delights embraced smoky bacon and honey with roasted chestnuts and toasted pine nuts on a bed of warm cereals and roasted sweet potato. Medicinal notes danced around a central mound of ash and charcoal as treacle drizzled down from above. Then fruity notes emerged that combined baked pineapple with orange skin and lemon drizzle cake. Water shifted the focus towards medicinal and coastal flavours as clean bandages lay strewn over seaweed and rock pools. Roast vegetables now appeared from the oven, glazed with honey, tarragon and thyme. Hints of pipe tobacco, liquorice and nutmeg merged on a finish that was dry, clean and laden with sea salt.'
  },
  {
    name: 'Fragrant, fresh and green',
    caskNumber: '26.152',
    price: '115',
    flavourProfile: 'Young & spritely',
    age: '8',
    date: 'September 2011',
    region: 'Highland Northern',
    caskType: 'Second-fill barrel',
    abv: '58.0',
    bottleOutturn: '259',
    allocation: '90',
    description: "Fragrant aromas explored sweet perfume, nuts and ripe fruits as roses merged with pineapples, kumquat and a rush of red apples. Oily overtones then suggested peach yogurt, cinnamon butter and linseed oil on a cricket bat. On the tongue a short burst of chilli heat quickly softened mango and papaya wrapped in the velvety textures of cream, melted butter and coconut oil with hazelnuts. Waxier notes appeared with water and nudged us towards citrus oils and spruce trees. Fresh and green tones embodied melon and green banana with tinned pears and sour apple rings. On the finish came green tea and cedar wood with a hint of camphor and mint milk chocolate."
  },
  {
    name: 'Heart of gold',
    caskNumber: '46.100',
    price: '375',
    flavourProfile: 'Old & dignified',
    age: '27',
    date: 'November 1992',
    region: 'Speyside Lossie',
    caskType: 'First-fill Spanish oak Pedro Ximenez hogshead',
    abv: '53.2',
    bottleOutturn: '259',
    allocation: '90',
    description: "We unanimously agreed it was a glorious nose, overflowing with beeswax, varnish, jasmine tea, hessian, toasted juniper wood, old ink wells, polished leather, cranberry gravy and black liquorice. Sumptuous, old school sherry of the highest calibre. Reduction gave us Black Jack chews, brown sugar, fruit scone mix, maraschino cherry juices and slightly salty bodega funk. The neat palate was fulsome, rich and darkly fruity with rancio, walnut oil, balsamic, quince paste, green walnut liqueur, black forest gateau and hessian. With water, we found salted almonds, bitter chocolate, biscotti, Vin Santo, volcano cake with extra strawberry jam and all manner of exotic hardwoods and toasted spices. The finish was full of soft waxiness, mineral oils, fennel tea and a wee bite of paprika. Sublime! Matured for 25 years in a bourbon hogshead before transferred to a 1st fill Spanish oak PX hogshead."
  },
  {
    name: 'From the garden to the kitchen and back',
    caskNumber: '113.36',
    price: '90',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '8',
    date: 'January 2012',
    region: 'Speyside Spey',
    caskType: 'Second-fill barrel',
    abv: '61.8',
    bottleOutturn: '209',
    allocation: '72',
    description: "The initial nose suggested to us the warmth of ginger nut biscuits dunked into chai tea. These soft spicy qualities were further underpinned by hot cross buns, dry cereals, brown toast with butter and some vibrant notes of golden syrup and citrus flowers. Reduction brought custard creams, sweetened herbal teas, hyacinths and honeysuckle. The neat palate was rich with barley sugars, orange pith, lime cordial and malty red ale notes. Wee background touches of dried tarragon, chalk and travel sweets popped out too. Water offered up ripe yellow fruits, custard made with young dessert wines, runny honey, camphor and aromatic new leather."
  },
  {
    name: 'Norse Mythology',
    caskNumber: '10.199',
    price: '145',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '10',
    date: 'September 2009',
    region: 'Islay',
    caskType: 'First-fill Pedro Ximenez hogshead',
    abv: '59.0',
    bottleOutturn: '286',
    allocation: '84',
    description: "The aroma of this one neat drew us deeper and deeper into the glass – we were sucked in and felt we were losing control as words like epic, wow and unbelievable were uttered. We just had to try it and it was breath-taking. Have you ever enjoyed traditional Hawaiian cooking called Kalua - where a hardwood fire is built inside a pit and a whole pig gets roasted over it for hours and hours?  Add a drop of water and we felt it was like a jötunn potion, perfect to warm up after skinny-dipping on a cold moonlit night.  After eight years in an ex-bourbon hogshead, we transferred this whisky into a 1st fill PX Sherry hogshead."
  },
  {
    name: 'After-dinner delights',
    caskNumber: '112.65',
    price: '140',
    flavourProfile: 'Spicy & sweet',
    age: '15',
    date: 'October 2004',
    region: 'Highland Southern',
    caskType: 'First-fill Limousin oak hogshead',
    abv: '56.4',
    bottleOutturn: '358',
    allocation: '72',
    description: "An intense dark sweetness emerged from the glass like chocolate fudge with hints of chipotle chilli, cinnamon and red pepper, a freshly varnished ebony cabinet or a chest of finest black loose tea. The taste neat stayed dark – cloves, peppercorns, cinnamon and plum black tea possibly served with a Sachertorte (dense chocolate cake with a layer of apricot jam and coated in chocolate icing). Diluted it turned into a deep, dark caramel sauce with raisins and on the palate a sweet coffee liqueur over Morello cherries. After twelve years in an ex-bourbon hogshead we transferred this whisky into a 1st fill Limousin oak hogshead."
  },
  {
    name: 'A vintage dinner suit',
    caskNumber: '66.174',
    price: '230',
    flavourProfile: 'Peated',
    age: '22',
    date: 'October 1997',
    region: 'Highland Eastern',
    caskType: 'Refill hogshead',
    abv: '56.1',
    bottleOutturn: '259',
    allocation: '90',
    description: "An air of sophistication rolled in as the butler, clad in a vintage dinner suit, presented us with a silver tray on which were neatly arranged cucumber sandwiches on white bread and venison carpaccio garnished with rosemary and thyme. Wonderfully fragrant champagne and gin cocktails arrived with a plume of lavender that remained fresh with elements of mint as floral smoke wafted past. Water was added from a crystal decanter to release notes of lime chocolate and walnuts. A sense of age brought us to an old wardrobe that once housed an engine driver's overalls, still reminiscent of mothballs and damp smoke. Finally an elegant platter was served of pickled herring, porcini mushrooms and roast beef followed by crackers, apricot pickle and virgin olive oil."
  },
  {
    name: 'Shades of black',
    caskNumber: '52.36',
    price: '140',
    flavourProfile: 'Oily & coastal',
    age: '13',
    date: 'March 2007',
    region: 'Highland Northern',
    caskType: 'First-fill Spanish oak Pedro Ximenez hogshead',
    abv: '59.2',
    bottleOutturn: '248',
    allocation: '90',
    description: "The soft fruits of apples, pears and tangerines merged with oloroso sherry before oily sardines joined flint rocks and wood char. Then sultanas and figs found sea salt covered chestnuts as we ventured onto a palate of ginger and liquorice. Juicy red wine notes of black cherries and jam joined burnt driftwood with salty notes suggesting brine. With water came salted dark chocolate, marzipan and hazelnuts with an obscure combination of hot cross buns and shellfish. Heavier oak now shone through with tree bark, cigar boxes and wood tannins but with black coffee, toasted barley and puffs of oily smoke that lasted long onto the finish. After spending 11 years in an ex-bourbon hogshead this was transferred to a 1st fill Spanish oak Pedro Ximenez hogshead for the remainder of its maturation."
  },
  {
    name: 'Winter walk hipflask',
    caskNumber: '38.28',
    price: '570',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '25',
    date: 'July 1995',
    region: 'Speyside Spey',
    caskType: 'Second-fill barrel',
    abv: '53.6',
    bottleOutturn: '241',
    allocation: '78',
    description: "Imagine chopped mixed fresh fruits, like apples, pears, bananas and pineapple all stewed in orange-flavoured sugar syrup and then set on fire with a brandy flame creating a fresh fruit flambé served with a topping of whipped cream. On the palate still plenty of fire ‘warming the cockles of our hearts’ with tropical fruits, spicy seasoned oak and a hint of ash – fascinating! Water and the floral fruitiness of orange and cherry blossom, as well as blooming magnolia trees, created an exotic perfumed scent which was followed by fruit scones with strawberry jam and a gingery sponge cake – ‘putting a spring in our step!’"
  },
];

export const aprilCasks: CaskAttributes[] = [
  {
    name: 'Assertively coastal',
    caskNumber: '53.349',
    price: '140',
    flavourProfile: 'Peated',
    age: '11',
    date: 'September 2008',
    region: 'Islay',
    caskType: 'Refill hogshead',
    abv: '57.3',
    bottleOutturn: '228',
    allocation: '120',
    description: 'Boldly medicinal with assertive coastal qualities. Lots of salted beach wood, mercurochrome, citronella candles, tar extract, naphthalene, mothballs, lanolin, waxy peat and shoreline bonfire embers. Wee touches of frying bacon fat, preserved lemons and black olives. Add a little water and out comes English mustard powder, embrocations, smoked scones, antiseptic, gauze and green peppercorns in brine. Some mechanical notes of tractor grease and dark roasted malts as well. The mouth is intensely briny and coastal. Full of plasticine, floor cleaner, mineral oils, petrolic aged riesling, raw lemon juice on fresh oysters and grilled whelks. With reduction it moves towards graphite, seaweed broth, smoked mussels and cullen skink laced with antiseptic.'
  },
  {
    name: 'Toffee tango and rhubarb rumba',
    caskNumber: '24.142',
    price: '350',
    flavourProfile: 'Spicy & sweet',
    age: '18',
    date: 'March 2002',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '57.4',
    bottleOutturn: '204',
    allocation: '102',
    description: 'Light and fruity aromas of pear drops and pineapple danced from the glass and paraded across pristine pine to find lemon curd on toast and sultanas dusted with allspice. A cha-cha of chilli heat and spearmint aroused the tongue before a samba of sweetness delivered honey, sherry trifle and cherry chocolate. With water came a tango of toffee and Turkish delight while a foxtrot of flowers brought carnations, roses and tulips with gooseberry jam and fresh pine wood. A waltz of warmth carried us through ginger and pink peppercorns as a final fling delivered toffee apples, strong black tea and bread and butter pudding.'
  },
  {
    name: 'Delightfully silky',
    caskNumber: '39.205',
    price: '110',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '9',
    date: 'September 2011',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '57.2',
    bottleOutturn: '235',
    allocation: '72',
    description: 'The nose brought gentle aromas that rolled over poached pears and sour lemon sweets as lemongrass merged into sweeter notes of cream-filled chocolate rolls and cereal characters. The mouth then became wrapped with delightfully silky textures that combined white chocolate mice with lemon oils and melted ice cream. With water, the citrus character moved to lemon curd and thick cream with shavings of lemon skin. Hints of caramelised red apples joined with plum jam while in the background lingered savoury elements and cashew nuts. Ice cream wafers now excited the palate with plenty of sweetness from sticky cocktails and dried apricots before rosewater and heavy fruit cake embraced the finish.'
  },
  {
    name: 'Dark and flaming',
    caskNumber: '112.66',
    price: '125',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '13',
    date: 'December 2006',
    region: 'Highland Southern',
    caskType: 'New oak hogshead, heavy char #4',
    abv: '64.4',
    bottleOutturn: '267',
    allocation: '90',
    description: 'The nose was deep, dark and mysterious – Demerara, treacle scones, rum and raisin, melted roofing tar, cough syrup, Euthymol toothpaste and polished wood. The palate didn’t just warm our cockles – it set them aflame – Madeira cake, black pepper, Fernet Branca, dark chocolate and marmalade cake, leather, liquorice root and clove-infused Muscovado. The reduced nose had medjool dates, malt loaf, molasses and manuka, Jamaica ginger cake and espresso dregs with brown sugar. The palate – syrup of figs, pipe tobacco, crème de cassis, treacle, dark cherries and venison cooked in port. After 11 years in ex-bourbon wood, we transferred this into a new oak, heavy char hogshead.'
  },
  {
    name: 'Intrigued? You should be.',
    caskNumber: '135.24',
    price: '115',
    flavourProfile: 'Spicy & sweet',
    age: '12',
    date: 'September 2007',
    region: 'Highland Southern',
    caskType: 'First-fill charred red wine barrique',
    abv: '57.0',
    bottleOutturn: '279',
    allocation: '108',
    description: '“This reminds me of lemon zabaglione with blueberries” which was followed by the comparison to “clementine possets with cranberry compote and cinnamon puff pastry palmier to dip” – intrigued?  You should be! On the palate elegant and measured with tannins that gave structure and the persistence of red berries laced with notes of liquorice and coffee. Add a drop of water a berry fresh fruit salad with a honey-lime dressing unveiled its charm and to taste mixed spices in a blueberry cake batter. After ten years in an ex-bourbon hogshead, we transferred this whisky into a 1st fill charred red wine barrique.'
  },
  {
    name: 'Railway track to a log cabin',
    caskNumber: '122.34',
    price: '105',
    flavourProfile: 'Young & spritely',
    age: '6',
    date: 'April 2014',
    region: 'Highland Southern',
    caskType: 'Second-fill barrel',
    abv: '62.2',
    bottleOutturn: '232',
    allocation: '72',
    description: 'The nose suggested muddy leather boots, Brasso cloths, smoked sea salt and incense – then we were walking on old railway sleepers laid over shale through a eucalyptus forest. The palate was medicinal (Vicks VapoRub, Buckley’s cough medicine) but also had pickles, salted crackers, wood embers, Elastoplast, liquorice imps, black tea leaves, tar, coal smoke and chimney scrapings. The reduced nose discovered mothballs, Camp coffee, TCP, creosote and we pictured eating salt and vinegar crisps by a log cabin fireside; eventually honey, menthol sweets and Kendal mint cake emerged. On the palate now, prawn cocktail and smoky bacon crisps, hints of ouzo and old herbal liqueurs.'
  },
  {
    name: 'Dining by the harbour',
    caskNumber: '4.264',
    price: '140',
    flavourProfile: 'Oily & coastal',
    age: '12',
    date: 'January 2008',
    region: 'Highland Island',
    caskType: 'First-fill barrel',
    abv: '61.4',
    bottleOutturn: '254',
    allocation: '90',
    description: "We cooked rainbow trout with lemony caper butter on the beach over a peat fire while we nibbled on slices of toasted coconut bread spread with a creamy pineapple jam made from singed cloves, thyme and sage.  Water added more of the lemon juice and salt with barbequed pineapple slices drizzled with smoked Scottish seaweed. On the palate we were served gambas a la plancha – Spanish style grilled shrimp tapas, whole unpeeled shrimps salted then cooked quickly with lemon juice – pure, simply delicious! At nine years of age, we combined selected hogsheads from the same distillery into a variety of different casks to marry. This is one of those casks."
  },
  {
    name: 'Graceful elegance',
    caskNumber: '125.77',
    price: '315',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '15',
    date: 'February 2005',
    region: 'Highland Northern',
    caskType: 'First-fill ex-Bodega Ximenez Spinola Pedro Ximenez barrique',
    abv: '58.1',
    bottleOutturn: '196',
    allocation: '84',
    description: "A subtle tropical and floral scent, like walking through a rose garden, mesmerized us. To taste a sense of spicy oak before a burst of juicy fruity flavours surprised us all. With a drop of water wax candles and veneered oak at first were soon followed by chilled caramelised orange slices with Greek yoghurt. On the palate now a summer delight with a difference; sweet succulent cherries with Neufchatel cheese sprinkled with Mexican cocoa powder; containing cinnamon and vanilla served with a thin, crisp chocolate cookie. After thirteen years in a 2nd fill bourbon barrel, we transferred this whisky into a 1st fill barrique from a privately owned small bodega, now in its 9th generation, that focuses exclusively on the Pedro Ximenez grape."
  },
  {
    name: 'Waxing tropical',
    caskNumber: '26.158',
    price: '120',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '9',
    date: 'September 2011',
    region: 'Highland Northern',
    caskType: 'Second-fill barrel',
    abv: '59.2',
    bottleOutturn: '257',
    allocation: '96',
    description: "Buckets of vanilla and creamy textures led us to buttery croissants served with quince jelly and apricot jam. Then rum and raisin ice cream joined lemons and coconut as we moved towards fresh oak coated with a fine layer of wax. On the palate came apples baked with raisins followed by pineapple juice and tropical fruit jelly sweets. With water, a more fragrant side appeared as rose water and chocolate-covered Turkish delight fused with marzipan and malted cereals while again waxy notes arrived. A burst of tropical fruits exploded on the tongue with a syrupy sweetness before sponge cake and melted butter on crumpets complimented sweet wood and pipe tobacco."
  },
  {
    name: 'Desire lines',
    caskNumber: '12.43',
    price: '545',
    flavourProfile: 'Old & dignified',
    age: '28',
    date: 'November 1991',
    region: 'Speyside Lossie',
    caskType: 'Second-fill Sherry butt',
    abv: '54.8',
    bottleOutturn: '387',
    allocation: '102',
    description: "Salted caramel chocolate at first, then greengage, cocoa, aged sweet Chenin from the Loire and madeira sponge cake. A dram that induces hushed silence. It continues with melon liqueur, raspberry cordial, muesli, spiced dark fruits, rum cocktails, gingerbread and figs in syrup. A rather humbling complexity. Reduction brings savoury umami, dense chocolate, black pepper warmth, nutty, meaty and bready qualities. Leaf mulch, aged cigars, red chilli and leathery game meats. The mouth upheld this dazzling complexity with brown bread smothered in treacle, caramelising brown sugar, toffee apples, cider brands, blackcurrant cordial, bread pudding, sugary black tea and bitter marmalade. Water brought aged calvados, old white balsamic, endless dark fruits, wintergreen, cough sweets, dried marjoram and a kind of herb-tinged sooty waxiness. Sublimely complex and mesmerising."
  },
  {
    name: 'A slow sipper',
    caskNumber: '10.197',
    price: '125',
    flavourProfile: 'Heavily peated',
    age: '6',
    date: 'October 2013',
    region: 'Islay',
    caskType: 'Re-charred hogshead',
    abv: '60.0',
    bottleOutturn: '279',
    allocation: '72',
    description: "Very peaty, very meaty!! Barbecue with smoky bacon, smoky duck, smoky venison and smoky sage sausages – I think you get the picture! Big and powerful on the palate neat with plenty of heat but at the same time, the sweetness and richness of burnt, charred malt, dark fruits, brown sugar and buttery caramel often found in very dark Scottish ale. Water added a briny, slightly oily aroma to the smoke – we added mackerels to the barbecue and they sizzled hot with plenty of ginger, garlic and black pepper. To taste now, a surprising sweet fruitiness of peaches and pears even a hint of vanilla but still with plenty of coastal smoke."
  },
  {
    name: 'A wooden sweet factory',
    caskNumber: '35.267',
    price: '310',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '25',
    date: 'November 1994',
    region: 'Speyside Lossie',
    caskType: 'First-fill toasted oak hogshead',
    abv: '57.9',
    bottleOutturn: '174',
    allocation: '36',
    description: "The nose had sweet, enticing, bourbon-like aromas – honeycomb crunch, salty-sweet Tiffin with sultanas and raisins, roasted pumpkin, jasmine, sandalwood and men’s hand moisturiser – along with Darjeeling tea leaves, toasted almonds and a leather workshop. The neat taste was immense, intense and mouth-drawing – woody and dry but with the considerable sweetness of toffee apple sticks, churros dipped in chocolate, candy corn, maple syrup pancakes, crystallised oranges and port over ice-cream. In reduction, the nose evoked a sweet factory built with wood, stewed fruits, brown sugar, apples, pears and piña colada. The palate fascinated us with salted fudge, treacle, chocolate gingers and cinnamon buns with raisins."
  },
  {
    name: 'Clingy combinations',
    caskNumber: '68.50',
    price: '100',
    flavourProfile: 'Spicy & sweet',
    age: '9',
    date: 'March 2011',
    region: 'Highland Southern',
    caskType: 'Re-charred hogshead',
    abv: '57.2',
    bottleOutturn: '260',
    allocation: '90',
    description: "A sticky combination of marmalade, honey and sugar syrup coated coconut and dark chocolate as citrus oils were released from orange and physalis. On the palate came a rush of orange vitamin pills and lime zest but now with toasty cereal notes, butter pastry and spicy cassia bark. Water lifted the aromas to release vanilla and apples along with soft fudge and strawberry laces. Orange now merged with buttered crumpets and the riper character of blood oranges found a sweet and spicy palate. Finally, flavours swirled lemons and limes around the mouth with caramel wafers and hints of wood char and cloves on the finish."
  },
  {
    name: 'The dram of the falling leaves',
    caskNumber: '44.133',
    price: '125',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '12',
    date: 'September 2007',
    region: 'Speyside Spey',
    caskType: 'Refill hogshead',
    abv: '57.0',
    bottleOutturn: '289',
    allocation: '90',
    description: "A heavy drizzle of golden syrup oozed over deep exotic fruits whilst dry and crispy leaves fell from autumn trees. Wisps of spicy incense merged with lavender to calm the mind in preparation for a mouth-watering palate that arrived with dark chocolate and plum stones. Luscious oils from oranges and nuts unravelled tight knots in preparation for a sweet treat of bakewell tarts. A little water delivered bowls of dried apple chunks and pear drops whilst violets lifted us to higher realms. A fresh undercurrent of cut grass remained to balance sweet fruitcake topped with milk chocolate and caramel. Finally a twist of squirty cream introduced silky textures that played with the dry spice of nutmeg."
  },
]

export const aprilMidMonthCasks: CaskAttributes[] = [
  {
    name: 'A wedding invitation',
    caskNumber: '72.93',
    price: '100',
    flavourProfile: 'Young & spritely',
    age: '9',
    date: 'February 2011',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '61.4',
    bottleOutturn: '220',
    allocation: '90',
    description: "Fresh flowers brought elegant aromas of honeysuckle and orange blossom with the sweetness of pink wafers and chilli chocolate. Then fruity notes appeared, combining jelly sweets with overripe bananas and slices of lime in a mojito cocktail garnished with eucalyptus leaves. Peppery notes of fresh ginger swirled on the palate before mellowing to ginger marmalade with Earl Grey tea and a dark espresso served with liquorice. Floral and fruity notes remained dominant with water as geraniums and red roses merged with blackcurrant jelly and pineapple sweets. An abundance of vanilla now eluded to sticky cake mix rich in sultanas, hazelnuts, cinnamon and nutmeg. White chocolate, praline and buttery icing were ready to top the cake as crystalised ginger and cloves transpired on the finish."
  },
  {
    name: 'Never-ending',
    caskNumber: '59.63',
    price: '105',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '10',
    date: 'February 2010',
    region: 'Highland Northern',
    caskType: 'Refill hogshead, heavy toast/medium char',
    abv: '57.8',
    bottleOutturn: '291',
    allocation: '66',
    description: "Sweet and malty notes combined freshly milled barley with buttered rye bread and nutty aromas as toffee apples merged with banana skins and marmalade. The palate was vibrantly fruity with a barrage of mango, papaya, guava and pineapple before biscuity notes returned in treacle and maple syrup. With water came elements of soft leather and antique wood covered with beeswax polish and dripping candle wax as fermenting apples joined soft pears. Strawberry jam and plums now emerged on the palate with banoffee pie and fruit scones coated with cinnamon butter. Nut and cereal flavours returned on an endless finish that incorporated mint chocolate with hazelnuts and polished oak. After spending 8 years in an ex-bourbon hogshead this was transferred to a heavy toast refill hogshead for the remainder of its maturation."
  },
  {
    name: 'Wonderfully deep',
    caskNumber: '68.52',
    price: '130',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '13',
    date: 'January 2007',
    region: 'Highland Southern',
    caskType: 'First-fill Pedro Ximenez butt',
    abv: '58.8',
    bottleOutturn: '534',
    allocation: '120',
    description: "We firstly commented on the wonderful deep colour of shiny conkers before the aroma became full of chocolate brownies, rum and raisin fudge, treacle toffee, tobacco, polished wood and a sweet coffee liqueur. Plenty of warming spices on the palate neat; nutmeg and garam masala before chocolate mousse, banana bread and caramel sauce appeared.  Water added cherries in the form of red velvet choc-cherry cupcakes and milk chocolate infused with zesty natural orange, while to taste: death by chocolate cake! After eleven years in an ex-oloroso butt, we transferred this whisky into a 1st fill PX sherry butt."
  },
  {
    name: 'Pleasingly idiosyncratic',
    caskNumber: '93.149',
    price: '120',
    flavourProfile: 'Lightly peated',
    age: '8',
    date: 'March 2012',
    region: 'Campbeltown',
    caskType: 'First-fill barrel',
    abv: '60.7',
    bottleOutturn: '234',
    allocation: '90',
    description: "Aromas you just have to love; oily rags, old polish cloth, cider washed cheese rind and a rusty bike chain or indeed puffing from a pipe filled with heritage tobacco while cutting the grass with a ‘smoking’ vintage lawnmower. On the palate neat like burnt aubergines, heavily charred over a cast-iron griddle, and then pureed with a splash of olive oil and lemon. When we added water, the sweetness and spiciness of a peppercorn sauce emerged at first before a hint of birch tar and clove-spiced dried orange peel took over. To taste very savoury, like a slice of smoked duck pizza with hoisin and scallions."
  },
  {
    name: 'The storm-tossed sea',
    caskNumber: '10.200',
    price: '125',
    flavourProfile: 'Peated',
    age: '6',
    date: 'October 2013',
    region: 'Islay',
    caskType: 'Second-fill charred red wine barrique',
    abv: '60.3',
    bottleOutturn: '285',
    allocation: '120',
    description: "The smoke of cherry flavoured pipe tobacco was creeping through a web of vanilla, leather and citrus next to a well-oiled engine going full throttle. Big and bold on the palate neat like chewing on charcoal glazed with honey or eating Tuscan drunken chestnuts – roasted and then flambéed with sugar and spiced rum. With the addition of water, we imagined sitting in the cabin of an old fishing boat on a storm-tossed sea, while to taste we were westering home in calm waters with Swedish snus placed in our upper lips. After five years in an ex-bourbon hogshead we transferred this whisky into a second-fill charred red wine barrique."
  },
];

export const mayCasks: CaskAttributes[] = [
  {
    name: "The panel's pun polestar",
    caskNumber: '84.35',
    price: '120',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '12',
    date: 'March 2008',
    region: 'Speyside Spey',
    caskType: 'First-fill Pedro Ximenez hogshead',
    abv: '56.8',
    bottleOutturn: '270',
    allocation: '90',
    description: "The nose wafted elusive scents of blackcurrant flowers, tinned lychees and fag packets – but mainly it offered sultanas, dates and figs, custard tarts, maple syrup and orange boxes. Orange notes dominated the palate – Grand Marnier and clove-studded orange in mulled wine – plus barley sugars and cinnamon balls, with toasted oak, liquorice and tobacco on the finish. On the reduced nose, we got Rum Baba, brown sugar, maple candies, dark chocolate orange and candied angelica. The palate became bitter-sweet with dark chocolate, pecans, plum stones, ginger and root beer. After 10 years in ex-bourbon wood, we moved this into a first-fill PX hogshead."
  },
  {
    name: 'Turn me inside out',
    caskNumber: '46.104',
    price: '125',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '13',
    date: 'March 2007',
    region: 'Speyside Lossie',
    caskType: 'First-fill Sauternes barrique',
    abv: '57.2',
    bottleOutturn: '292',
    allocation: '120',
    description: "A wonderful aroma of freshly squeezed waxy oranges, warm gingerbread, grape noble rot and fruitcake laden with booze-soaked sultanas greeted us. Inviting, heady, complex and oozing lusciousness. Dark toffee, black bun, cassis and cinnamon swirls topped with stewed fruits. Water brought a creamy fatness to proceedings. Dark chocolate, pears poached in Calvados, treacle scones and plum duff with a splash of brandy. The palate initially revealed an unctuous sweetness. A whole mouthful of gooey dark fruits, flapjack, parkin, chantilly cream with citrus zest and then caramelising brown sugar with Chinese five spice. Water brought more brandy richness, spun sugar, aged muscat, apple turnovers and wild strawberries. Matured for 11 years in a bourbon hogshead before being transferred to a first fill sauternes barrique."
  },
  {
    name: 'Brings a sheen to the glass',
    caskNumber: '7.254',
    price: '160',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '16',
    date: 'November 2003',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '56.6',
    bottleOutturn: '211',
    allocation: '90',
    description: "One panellist made full use of the pick ‘n’ mix sweet counter filling his bag with fizzy apple snakes, cherry lips, foamy bananas and fried eggs and while he was at it, let’s have a vanilla custard slice to round it all off.  On the palate we had a watermelon smoothie, finger limes, shortbread and a refreshing frozen berry and coconut cheesecake. Water added an earthy vibe, like walking through a botanical garden or a fruit market on Madeira as we sat down for a break and popped open a bottle of slightly sparkling, frizzante, Lambrusco wine; fruity flavours paired with an elegant acidity."
  },
  {
    name: 'Bounty on the galleon',
    caskNumber: '107.21',
    price: '110',
    flavourProfile: 'Spicy & sweet',
    age: '8',
    date: 'March 2012',
    region: 'Speyside Spey',
    caskType: 'First-fill Sherry butt',
    abv: '63.3',
    bottleOutturn: '210',
    allocation: '90',
    description: "A Spanish galleon laden with hessian sacks full of spices, dates, figs, raisins and demerara sugar made an emergency stopover in Madeira as in the wardroom some of the officers had started a small fire by not fully extinguishing their cigars. While the repair took place, we were offered a decadent lunch – slow cooked roast Seville orange-glazed duck served with red cabbage and a madeira wine gravy. After some water we washed it all down with a very old and very rare Terrantez vintage Madeira wine. Back on board we exchanged views and while some absolutely loved the hospitality on the island, others were not quite so sure."
  },
  {
    name: 'It shines',
    caskNumber: '1.236',
    price: '120',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '9',
    date: 'April 2011',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '59.3',
    bottleOutturn: '229',
    allocation: '60',
    description: "This was proper Perry, bottle-fermented Perry, a delicate sweetness with tropical fruit aromas of guava and pineapple as well as a hint of citrus – Napoleon allegedly described it as “English champagne”. Talking of sparkling on the palate like a Moselle kir royale, dry sparkling Riesling wine mixed with red Moselle vineyard peach liqueur. With a drop of water, we added the liqueur to spicy chutney or caramelised it until crispy on top of a panna cotta. To taste remarkably fresh and fruity, somewhat sharp but with the sweet magic of pink chocolate truffles with milk chocolate, butter and Marc de Champagne centre."
  },
  {
    name: 'Bivouac breakfast',
    caskNumber: '66.186',
    price: '120',
    flavourProfile: 'Peated',
    age: '11',
    date: 'November 2008',
    region: 'Highland Northern',
    caskType: 'Refill barrel',
    abv: '58.1',
    bottleOutturn: '245',
    allocation: '120',
    description: "In a secluded forest, the first rays of sunlight illuminated green moss and ferns as a hot iron griddle pan sizzled and hissed over a smoky campfire. From the pan came wondrous fast-busting aromas of crispy bacon and strips of fatty pork belly while wafts of peanut butter merged with charcoal and morning dew. Flavours then cascaded around dry roasted peanuts, smoked paprika and sweet liquorice before roasted vegetables complimented smoked ham. A dash of pure water introduced an entirely impure dimension as we stumbled across an old work shed with heavy leather welder's gloves, tins of engine oil and a mechanics overalls. Smoke from the campfire was still thick in the air but now fused with pecan pie and Lapsang souchong tea."
  },
  {
    name: 'The dark lure',
    caskNumber: '35.272',
    price: '155',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '16',
    date: 'August 2003',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '58.3',
    bottleOutturn: '193',
    allocation: '96',
    description: "We discovered an inviting array of aromas on the nose neat, ranging from spearmint to tropical fruits (pineapple and bananas), pear drops, pine resin, almond oil and finally a warm chocolate marzipan croissant. Velvety smooth on the palate reminded us of slightly burnt toasted coconut chocolate chip cookies – but we enjoyed the dark lure! With a drop of water we carried a wooden box of fresh oranges. We cut one in half and drizzled it over melted chocolate to make ginger cookies with an orange chocolate buttercream and, whilst they were in the oven, we enjoyed a slice of cherry and pistachio cake."
  },
  {
    name: "Life's simple pleasures",
    caskNumber: '13.82',
    price: '115',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '7',
    date: 'April 2013',
    region: 'Highland Northern',
    caskType: 'First-fill Cosecha wine barrique',
    abv: '58.9',
    bottleOutturn: '235',
    allocation: '90',
    description: "An inviting bouquet of aromas greeted the Panel; Earl Grey tea, fig rolls, raisins and dates as well as sweet walnut wine, three fruit marmalade and cocoa powder. On the palate a little luxurious; pan-seared foie gras on toasted brioche with mildly nutty mache and creamy white wine puree. With a drop of water, sweet earthy notes emerged - bubbling brown sugar and flavours from Jamaica (coffee and rum) as we kept indulging ourselves in a sweet moment eating dark chocolates with creamy soft ginger-flavoured filling – one of life’s simple pleasures. After five years in an ex-bourbon hogshead we transferred this whisky into a first fill French oak barrique."
  },
  {
    name: 'The upside-down',
    caskNumber: '115.20',
    price: '390',
    flavourProfile: 'Old & dignified',
    age: '26',
    date: 'April 1994',
    region: 'Speyside Deveron',
    caskType: 'First-fill barrel',
    abv: '45.4',
    bottleOutturn: '132',
    allocation: '60',
    description: "A surprisingly youthful and fresh nose, full of readily muddled green herbs, garden flowers, ginger beer, rosehip tea and chamomile. A nibbled of white pepper alongside golden syrup and lychee. A big dollop of pineapple jelly too. Reduction brought putty, horseradish and other spicy things. Some fresh cigarette papers, cornflour, chamois leather and lightly honeyed porridge. The palate was bold, nourishing and full of marzipan, stone fruits, eucalyptus resin, mint julep and old school shilling ales. With water we found a warmth of pepper, soft earthiness, waxes, herbal teas, grassy olive oil and lemon rind. A wee dazzler!"
  },
  {
    name: 'Trekking in the jungle',
    caskNumber: '48.118',
    price: '90',
    flavourProfile: 'Young & spritely',
    age: '7',
    date: 'November 2012',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '60.6',
    bottleOutturn: '251',
    allocation: '72',
    description: "We made cilantro mint chutney using Greek style natural yoghurt, fresh cilantro, ginger, jalapeno, garlic, mint and lemon juice to accompany our vegetable samosas. On the palate neat we had Kendal mint cake, that sugar-based confection flavoured with peppermint, popular among British climbers as a source of energy. In our case however they were laced with chilli flakes for an extra oomph. After the addition of water we imagined walking through mountain grassland, a cooling herbal, green, fresh breeze as we gathered strength for our ascent to a snow-capped mountain peak. Having reached the top we cooked on a tiny gas stove a delicious tom yam soup."
  },
  {
    name: 'Put the pebble to the petal!',
    caskNumber: '26.161',
    price: '115',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '8',
    date: 'April 2012',
    region: 'Highland Northern',
    caskType: 'First-fill barrel',
    abv: '60.9',
    bottleOutturn: '231',
    allocation: '96',
    description: "The initial nose was one of putty and clay on waxed canvass. Then baking parchments, soda bread, crushed chalk, white pebbles, sea greens, pineapple jelly and gorse flowers. A big spoon of honey stirred into some salty porridge. Reduction brought a light sootiness and some brighter, more direct waxy tones. Hints of mirabelle, condensed milk and green tea with lemon. The palate was initially rather light and playful with notes of juniper, violet sorbet, mint julep, lemon icing and fabric softener. Starched linens and breakfast cereals dusted with icing sugar. With water we got wildflowers, bubble-gum and a concentrated note of geraniums in a hot greenhouse. Some mustard warmth and bubble-gum fruitiness in the aftertaste."
  },
  {
    name: 'The gentle beast from the east',
    caskNumber: '56.0',
    price: '94.10',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '13',
    date: 'August 2007',
    region: 'Highland Northern',
    caskType: 'First-fill Pedro Ximenez hogshead',
    abv: '56.0',
    bottleOutturn: '263',
    allocation: '72',
    description: "There was an unhurried, timeless quality about this bouquet of aromas; full of fruit (plums and blood oranges), spice (cinnamon and nutmeg), oak and roasted almonds. On the palate we were wandering in a PX wonderland with notes of caramelised pecans, dark cherries soaked in rum, dark plums, violet and strawberry fruit flavoured loose leaf black tea – this is an absolute lip-smacker! Careful when adding water, the scent of marzipan, caramel orange shortbread and malt extract was followed by a glass of Lambrusco – an off-dry lightly sparkling red wine – an absolute joy from start to finish! After eleven years in a refill ex-bourbon hogshead, we transferred this whisky into a 1st fill PX sherry hogshead."
  },
  {
    name: 'A trip to the exotic market',
    caskNumber: '9.186',
    price: '155',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '16',
    date: 'September 2003',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '53.2',
    bottleOutturn: '214',
    allocation: '90',
    description: "Plenty of sweet goodness on the nose neat; vanilla panna cotta with fresh strawberries and a good dash of grappa as well as a sweet, spiced apricot smoothie. On the palate neat an orange and lime crème caramel with that surprise citrus burst and the various spices from the smoothie – cinnamon, ginger and chai seeds. With a little water we had a soft scoop vanilla ice cream and white chocolate-dipped caramel fudge fingers. To taste, pure magic!  A smoky tea-infused Manhattan using sweet vermouth, Angostura bitters and Lapsang Souchong black tea, garnished with a cocktail cherry and a slice of orange."
  },
  {
    name: 'Dances on the tongue',
    caskNumber: '112.77',
    price: '120',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '12',
    date: 'March 2008',
    region: 'Highland Southern',
    caskType: 'Second-fill barrel',
    abv: '59.1',
    bottleOutturn: '209',
    allocation: '60',
    description: "Tart citrus aromas of kumquat and lime mixed with sweet orange fondant and digestive biscuits while a perfumed fragrance brought delicate rosewater and gorse bushes in bloom. The palate was vibrant and fresh with a peppery spice that tingled and danced on the tongue as popping candy merged with fresh mint leaves. Sweet fragrance remained but now with scented beeswax, banana skins and toasted pine nuts. Water brought us Oriental steamed buns filled with sweet bean curd and vanilla while quince jelly and nectarines continued a citrus feel. Finally, paper envelopes had been skilfully folded into decorative flowers to garnish rice wine as we enjoyed peppermint tea and dried papaya."
  },
  {
    name: 'Spinneys and hedgerows',
    caskNumber: '2.120',
    price: '160',
    flavourProfile: 'Spicy & sweet',
    age: '14',
    date: 'April 2006',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '54.0',
    bottleOutturn: '212',
    allocation: '96',
    description: "We found this one had a beautiful nose, brimming with freshness and sunshine. Notes of sun lotion, butter beans, starched linens, bramble bushes, potting shed floors and sourdough starter. Water brought out grassiness, moss, petrichor, vase water and damp ferns. Green, vibrant and vividly fresh. The palate when neat started with a kick of cinnamon, then went wonderfully rich and buttery. Lots of lemon sherbet, thyme, butter biscuit, soda bread spread with honey and a splash of lemon cordial. Reduction enhanced the fruitiness with pineapple jelly, fruit salad juices, crisp cereals, lemon balm and herbal cocktail bitters."
  },
  {
    name: 'Holy smoke!',
    caskNumber: '29.277',
    price: '350',
    flavourProfile: 'Old & dignified',
    age: '19',
    date: 'February 2001',
    region: 'Islay',
    caskType: 'Refill Oloroso butt',
    abv: '56.1',
    bottleOutturn: '210',
    allocation: '90',
    description: "Wow! Smoked honey-glazed ocean trout barbequed on cedar planks next to crispy bacon waffles as we reminisced of a perfect day on the beach when we explored rockpools and caves. As the sun set over the sea, we lit the tiki torches and the atmosphere turned electric. On the palate neat it felt like a sweet, warm embrace – flavours of bergamot, lavender, orange oil, maple syrup and molasses honey on dark chocolate chip muffins – holy smoke! We all agreed it did not need water, however an aroma of spicy sweet cigar smoke mingled with the scent from firing a flintlock pistol while to taste sweet dark sea salt smoky chocolate."
  },
  {
    name: 'Fluttering fan-waft of fruit',
    caskNumber: '77.66',
    price: '120',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '12',
    date: 'August 2007',
    region: 'Highland Northern',
    caskType: 'Re-charred hogshead',
    abv: '59.2',
    bottleOutturn: '260',
    allocation: '48',
    description: "A complex nose of jasmine, hibiscus flowers, refreshers, delicate waxiness and a fluttering fan-waft of fruity aromas – dried mango, peaches, raspberry and Kir Royale. It had a fruity palate too – strawberry, cherry, redcurrants, pomegranate, lemon and young calvados – plus wild flowers and gorse, wood and tobacco. The intriguingly aromatic theme continued with water – rose gardens, Earl Grey tea and beeswax – and still cascading down that fruit chute – pineapple syrup, lemon curd, fruit leathers and raspberry Ruffle bars. The reduced palate – tutti frutti, juicy fruit chewing gum, guava, and apple crumble with custard – then sugar-coated fennel seeds, tea chests and pink peppercorns to finish."
  },
  {
    name: 'Decadent perfume of paradise',
    caskNumber: 'G5.14',
    price: '120',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '16',
    date: 'December 2003',
    region: 'Highland Northern',
    caskType: 'Second-fill barrel',
    abv: '64.3',
    bottleOutturn: '129',
    allocation: '90',
    description: "The nose invited us to lounge about on a haystack with a root beer ice-cream float which has additional hints of banana toffee, bourbon and vanilla pods. The palate had a similar effect – brown sugar sprinkled on banoffee pie, shimmerings of rum and coconut, and a finish of dusty wood and spiced sweets (ginger, aniseed, clove). The reduced nose transported us to a tropical island – cane sugar, vanilla pods, rum and gardenia blossoms – ‘a sweetly decadent perfume of paradise’. The palate now supplied dark chocolate, caramelised sugar, Madeira molasses cake and intriguing apothecary notes – once again a spicy finish, now nutmeg and wasabi."
  },
];

export const speysideFestivalCasks: CaskAttributes[] = [
  {
    name: 'Commands your attention',
    caskNumber: '63.72',
    price: '175',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '18',
    date: 'May 2002',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '49.3',
    bottleOutturn: '121',
    allocation: '121',
    description: "Two panellists were squabbling – dunnage warehouse or fruit cellar? A close thing at first but eventually the fruit triumphed – overripe melon, apples, pears and mango with a squeeze of lime – all quite exotic (also polished wood and tobacco). The taste had white chocolate jazzies, elderflower cordial, aged Meursault and once again that almost unbelievable fruitiness – apricot yoghurt, strawberry, kiwi and physalis. The reduced nose on this ‘commanding dram’ introduced camphor, cinnamon, lavender honey and charred oak to the magnificent mountain of fruit. On the palate now, we revisited a fruit bomb so juicy there wasn’t a dry chin in the house."
  },
  {
    name: 'Earthy and mysterious',
    caskNumber: '95.46',
    price: '100',
    flavourProfile: 'Spicy & sweet',
    age: '8',
    date: 'October 2012',
    region: 'Speyside Lossie',
    caskType: 'Second-fill charred red wine barrique',
    abv: '61.3',
    bottleOutturn: '275',
    allocation: '275',
    description: "The nose had spun sugar, vanilla slice, preserved plums, Morello cherries, crème de cassis, red wine lees and Barolo Chinato, also some earthy notes – half-smoked cigar, forest floor, leather. The palate conveyed dark sweetness – maple candy, overdone donut, baklava, cherry cake, etc. – but still that earthy, almost mysterious element – charred blackcurrant twigs, New York hot-dogs, oily wood and olive skins. In reduction – tea chests, wine vaults and Black Forest gateau soaked in kirsch on the nose, while the palate combined sharp, zesty notes with prune juice, mulled wine and goulash. After five years in ex-bourbon wood we transferred this into a charred red wine barrique."
  },
  {
    name: 'Aged to perfection',
    caskNumber: '113.41',
    price: '215',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '23',
    date: 'September 1997',
    region: 'Speyside Spey',
    caskType: 'Refill hogshead',
    abv: '54.3',
    bottleOutturn: '195',
    allocation: '78',
    description: "It seemed to quieten us all down almost immediately, similar to when you enter a library – and we discovered a hidden treasure, a throwback to those old-fashioned libraries with that wonderful smell of old leather books on dusty wooden shelves. Ridiculously mellow with the slight tartness of green apple and in the finish, a very light tobacco complemented by a refreshing eucalyptus flavour. A drop of water and we were in the cellar of a chateau, apples were stored in wooden crates ready to be made into cider and then distilled and matured finally into a quality calvados. This one was made from the Germaine variety, perfume and sweetness contributing to the overall roundness."
  },
  {
    name: 'The deepest of mahogany',
    caskNumber: '24.147',
    price: '155',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '12',
    date: 'October 2008',
    region: 'Speyside Spey',
    caskType: 'First-fill American oak Pedro Ximenez hogshead',
    abv: '63.3',
    bottleOutturn: '336',
    allocation: '90',
    description: "The smell was initially like opening a jar of candied pitted olives and cherries in sweet sherry. The cherry theme continued with cherry Bakewell tarts, cherry lips and fizzy cherry cola bottle sweets. The taste was something special; raisin concentrate, fig syrup and prunes in a sweet dark bitter chocolate sauce. Water added sticky toffee pudding and spiced poached pears in chocolate sauce before we washed it all down with a Kalimotxo cocktail - red wine and cola sangria spritzer. In 2018 we combined selected oloroso butts before returning the single malt to a variety of different casks to develop further. This is one of those casks."
  },
  {
    name: 'Floating through ferns',
    caskNumber: '9.194',
    price: '125',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '12',
    date: 'March 2008',
    region: 'Speyside Spey',
    caskType: 'Refill barrel',
    abv: '55.9',
    bottleOutturn: '230',
    allocation: '72',
    description: "We were on a beach; sand dunes with wildflowers and ferns surrounded us as we took juicy fat grilled prawns in a honey-ginger barbeque sauce off the grill. To drink we enjoyed pale ale from the Australian brewery Little Creature, chewy malts that tasted of caramel and toffee, with a gentle citrus and hoppy aftertaste. After we added water it felt like a breath of fresh air and on the palate we were all sucking ‘mouth-wateringly good Swiss herbal sweets’ using Moroccan mint and a 13 herb mixture or we chewed on soft jelly fruits with fresh fruit juice and lightly dusted in sugar."
  },
  {
    name: 'Worm tub stodge',
    caskNumber: '48.120',
    price: '90',
    flavourProfile: 'Spicy & sweet',
    age: '7',
    date: 'November 2012',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '60.0',
    bottleOutturn: '229',
    allocation: '90',
    description: "A bright and fresh nose full of stone fruits, torn mint leaf, chewy toffee and foam bananas. Playful, vivid and enticing. Some green apples, tinned peaches, pineapple cubes and hints of clove and tree bark added richness. Some water brought milk chocolate and orange travel sweets. Candied hazelnuts, warm custard and some poached rhubarb with brown sugar. The palate when neat was full of strawberries and meringue, tutti frutti and coconut milk with apricots. Water brought pecans and maple swirl ice cream, orange blossom, a hint of lavender and porridge laced with gooseberry jam."
  },
];

export const campbeltownFestivalCasks: CaskAttributes[] = [ {
    name: 'Unusually unique',
    caskNumber: '93.153',
    price: '145',
    flavourProfile: 'Oily & coastal',
    age: '11',
    date: 'September 2009',
    region: 'Campbeltown',
    caskType: 'First-fill barrel',
    abv: '57.3',
    bottleOutturn: '194',
    allocation: '194',
    description: "Vivid seaside memories envisioned candyfloss and seafood broth with sweet vanilla, motor oil and clean wool. The palate was abundant with the creamy notes of soft cheese mixed with candied pineapple and Turkish delight as honey glazed hazelnuts dipped in salt joined heather honey and medicinal suggestions. With water the creaminess turned to clotted cream served with sea buckthorn and waxed lemons. Floral flavours embraced heather and lavender with coconut and coriander seeds while heavier notes of liquorice and coffee grounds combined with light tobacco. Finally a little ginger warmth lasted onto a finish of mussels cooked in a sun lotion sauce and sprinkled with white pepper."
  },
];

export const highlandFestivalCasks: CaskAttributes[] = [
  {
    name: 'Hats off to Mr Ross',
    caskNumber: '78.42',
    price: '130',
    flavourProfile: 'Spicy & sweet',
    age: '11',
    date: 'September 2009',
    region: 'Highland Western',
    caskType: 'First-fill barrel',
    abv: '64.4',
    bottleOutturn: '202',
    allocation: '202',
    description: "An initial aroma of baked apples, sticky toffee pudding, condensed milk sweetness and melted butter. A little brown sugar underneath. With some time and air we got creamy coconut, sunflower oil and a rather fuller vanilla aroma. Good weight gives quite a 'textural' impression. With water we found some notes of cherry stones, red apples, new leather and baled hay. Rather aromatic and nicely punchy with plenty distillery character. The palate opened with a rich sweetness of butterscotch and custard with orange peel. Zesty, oily, balanced and fresh. A little peppery warmth from the oak. With water a nice balance between wood and distillate emerges; cherry ice cream, vanilla wafer and ginger alongside chewy malt and very light waxiness."
  },
  {
    name: 'Prohibition remedy',
    caskNumber: '112.70',
    price: '115',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '12',
    date: 'December 2007',
    region: 'Highland Southern',
    caskType: 'First-fill barrique, shaved/toasted/re-charred',
    abv: '57.0',
    bottleOutturn: '239',
    allocation: '90',
    description: "On the nose came a complex array of ripe apples and calvados with dark earthy notes of truffles, mushrooms and Madeira wine. Cloves, tarragon and sage pointed towards sticky cough syrup with baked oranges and coconut muffins providing sweetness. The palate was bound by sweet notes as a big explosion of toffee, fudge and strawberries powered towards cinnamon, nutmeg and plenty of ginger. Even more medicinal with water, we were now treated to fennel seeds, maple syrup and red liquorice reminiscent of a long-forgotten cough syrup. Textures coated the mouth like sticky sherry infused with juniper berries, rosemary and coriander seeds before nutmeg and menthol tobacco framed the finish. After spending ten years in an ex-bourbon hogshead this was transferred to a first fill barrique for the remainder of its maturation."
  },
  {
    name: 'A doric takeaway',
    caskNumber: '66.189',
    price: '100',
    flavourProfile: 'Lightly peated',
    age: '7',
    date: 'September 2013',
    region: 'Highland Eastern',
    caskType: 'First-fill barrel',
    abv: '61.4',
    bottleOutturn: '294',
    allocation: '108',
    description: "Savoury aromas of grilled bacon, pretzels and black pepper-coated peanuts nestled beside an abundance of toasty cereals and coal soot-dusted seaweed. In the mouth an exuberant spice was complemented by charred wood dipped in honey and vanilla icing over burning heather and applewood smoked ham. Oily notes emerged with water before salted liquorice and burning tar moved towards dried herbs and dark treacle on crispy rye bread.  A tingly palate now embraced menthol and peppermint with applewood smoked duck, baked orange and lemon skin while on the finish came barley sugar sweets and toasted fruit loaf."
  },
  {
    name: 'Surprising, inspiring, indulging!',
    caskNumber: '26.165',
    price: '155',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '10',
    date: 'September 2010',
    region: 'Highland Northern',
    caskType: 'First-fill barrel',
    abv: '56.4',
    bottleOutturn: '236',
    allocation: '120',
    description: "We all looked at each other and nodded, yes there is a hint of smoke – not much but noteworthy, maybe like a wax jacket which hung in a room with a burning peat fire. On the palate - delicious hot-smoked salmon and parsley fishcakes with a zingy lemon mayonnaise dip. After a drop of water, the aroma was even more mouth-watering - smoky grilled shrimps in a Marie Rose sauce and to taste; bananas flambeed Caribbean style using butter along with dark-brown sugar, dark rum and lime juice. The smooth finish had plenty of refreshingly lemony flavours with a gentle herbal note."
  },
  {
    name: 'From heather to moor to sea shore',
    caskNumber: '4.270',
    price: '140',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '12',
    date: 'January 2008',
    region: 'Highland Island',
    caskType: 'First-fill barrel',
    abv: '61.3',
    bottleOutturn: '244',
    allocation: '90',
    description: "This small batch Orcadian nectar was transferred into a first-fill bourbon barrel after nine years. The nose is bright and innocent – gorse and heather, singed lemon peel and custard tarts; a trickle of incense smoke shyly appears. The palate; more gallus than innocent, discovers pineapple humps, apricot Danishes, toffee, honey on toast, sweet coconut and oiled wood. The reduced nose gets iced lemon cupcakes, leather and jasmine hedgerows – a ramble from the heather moor to the shore. The palate now discovers rhubarb rock, green apple and heather stems dipped in heather honey; the finish finds green wood, black tea and quince jelly."
  },
  {
    name: 'Adventures by the sea',
    caskNumber: '42.54',
    price: '150',
    flavourProfile: 'Oily & coastal',
    age: '15',
    date: 'March 2005',
    region: 'Highland Island',
    caskType: 'Refill barrel',
    abv: '61.6',
    bottleOutturn: '184',
    allocation: '60',
    description: "We felt the need to sharpen an axe with a whetstone and inevitably an accident happened and as we opened the first aid box, all we saw were salted toffees, ginger cake and Turkish delight. Oh well, we managed as on the palate, we detected a lovely, intriguing interplay between sweet and salty, like popcorn and almonds but then also a ginger, sweet nutmeg spiciness in the finish. Fun activities came to mind after a splash of water, shelling on the beach, a picnic in a pine forest and a trip to the prawn shack as we finished with an olive oil martini."
  },
];

export const islayFestivalCasks: CaskAttributes[] = [
  {
    name: 'Smoky maritime hit',
    caskNumber: 'Distillery 10 Small Batch',
    price: '140',
    flavourProfile: 'Heavily peated',
    age: '7',
    date: 'October 2013',
    region: 'Islay',
    caskType: 'Second-fill Pedro Ximenez & re-charred hogsheads',
    abv: '59.6',
    bottleOutturn: '932',
    allocation: '932',
    description: "Sweet, smoked raisins, beech smoked prunes, smoked orange marmalade and chargrilled lobster served in a smoky balsamic sauce – in three words: massive, sweet smoke! However, nothing could prepare us for the taste neat, ‘we were going up in smoke’! Soy roast whole duck with a tangerine-hoisin glaze, salty, briny and ashy but at the same time it was like biting into a toffee apple - crunchy crackly caramel surrounding a juicy ripe apple. With water we dowsed a beach barbeque with sea water, opened a heather ale and had smoky candy floss before we ate a Reuben sandwich with homemade smoky Russian dressing and a spiced rum soaked Jamaican ginger cake accompanied by a ‘Phenol Espresso’."
  },
  {
    name: 'Madame Butterfly in the Garden of Eden',
    caskNumber: '3.316',
    price: '245',
    flavourProfile: 'Lightly peated',
    age: '16',
    date: 'February 2004',
    region: 'Islay',
    caskType: 'Second-fill hogshead',
    abv: '56.2',
    bottleOutturn: '178',
    allocation: '178',
    description: "Some whiskies take you to sunny places – this one trails you through gardens and orchards – the nose has orchard fruits; pear, peach then lemon cake, restrained lavender, geraniums, bog myrtle, flowering laurel and cherry blossom – also delicate wood smoke, ash and hints of leather. The palate has blackberry, melon, lavender honey and violet creams, but leans more to suggestions of seaweed, shrimp and langoustine, smoked fish and Earl Grey tea, with perfumed smoke – sweet, salty, smoky and silky smooth – one panellist saw ‘Madame Butterfly smoking a cigarette in the Garden of Eden’. The finish picks up stem ginger and sweet aniseed warmth."
  },
  {
    name: 'A green sea tapestra',
    caskNumber: '53.367',
    price: '145',
    flavourProfile: 'Peated',
    age: '10',
    date: 'September 2010',
    region: 'Islay',
    caskType: 'Refill hogshead',
    abv: '60.3',
    bottleOutturn: '265',
    allocation: '265',
    description: "Our noses twitched at the peat smoke, white pepper, Sudocrem and muscle rub, before discovering a green tapestry of smoky stewed spinach, moss on a dyke, seaweed sorbet, olives in brine and bread dipped in moules marinieres liquor. The palate was equally smoky, but somehow cleaner, even elegant – poached pears, oysters, pickled cucumber, sea-salt sherbet, thyme, samphire and smoked mackerel. New aromas on the reduced nose were cut grass, pea shoots, lime and eucalyptus; peanuts in shells, toasted sesame seeds, popcorn and swimming pools. The reduced palate remained substantially textured, with flavours of salted caramel, liquorice, pine sap and mint humbugs."
  },
];

export const juneOutturnCasks: CaskAttributes[] = [
  {
    name: "A dram of gratitude",
    caskNumber: '30.117',
    price: '260',
    flavourProfile: 'Old & dignified',
    age: '23',
    date: 'February 1997',
    region: 'Speyside Spey',
    caskType: 'First-fill Spanish oak Pedro Ximenez hogshead',
    abv: '61.2',
    bottleOutturn: '213',
    allocation: '213',
    description: "The bold sweetness of butterscotch and toffee coated the heavy fruits of figs, sultanas and Jamaica cake while a lorry load of spice delivered fenugreek, turmeric and Chinese five-spice. On the palate dark chocolate and dried ginger swirled in cinnamon whipped cream as cherry jam and concentrated sweet sherry joined cocoa powder on oak. With water came heavy fruit cake and nutmeg infused black forest gateau while dusty wine cellars concealed porcini mushrooms and leather. Then cardamom ice cream and biscuity cheesecake stumbled into demerara sugar and hazelnut butter with orange skin to finish. After spending 21 years in an ex-bourbon hogshead this was transferred to a Pedro Ximenez hogshead for the remainder of its maturation."
  },
  {
    name: 'Confessions of a barbecue',
    caskNumber: '16.53',
    price: '115',
    flavourProfile: 'Heavily peated',
    age: '11',
    date: 'December 2009',
    region: 'Highland Southern',
    caskType: 'Re-charred hogshead',
    abv: '61.1',
    bottleOutturn: '262',
    allocation: '262',
    description: "Thick plumes of smoke and engine grease blended with sticky Muscovado sugar caramelising on barbecued pork ribs, bananas and singed pineapple as hints of rum and vanilla embraced liquorice on pencil shavings. Scorched raisins on the palate introduced burning bramble bushes and soot mixed with butter on rye bread and squares of smoked chilli chocolate. More woodiness emerged with water bringing vanilla and creosote along with black olives sprinkled over flamed mackerel. Orange oil coated the mouth as prosciutto and the burnt ends of brisket swirled around cherry jam, malt loaf and enduring clouds of heavy wood smoke."
  },
  {
    name: 'The dark goes out',
    caskNumber: '26.164',
    price: '110',
    flavourProfile: 'Oily & coastal',
    age: '7',
    date: 'October 2013',
    region: 'Highland Northern',
    caskType: 'First-fill barrel',
    abv: '63.0',
    bottleOutturn: '226',
    allocation: '90',
    description: "A more tempestuous example of this legendary distillate. We found the nose initially prickling with antiseptic, bubble-gum, wind-lashed linens and canvass. Citronella wax, tutti fruit, dried seaweed in ramen broth and coal tar soap. Hefty but soothing and superbly 'zen'. With water we got heather flowers, pollen, sooty coal hearths, wood embers and scrunched newspapers. Some bone dry riesling and wet beach pebbles. The palate was initially bright and awakening with tar acidity, zippy minerals, lemon-scented candles and cough medicines. A squeeze of herbal toothpaste and touches of beeswax. Water made it more herbal and wonderfully mouthcoating. Rich, malty fatness, mineral oils, custard made with sweet wines and a saline kiss of ozone in the aftertaste."
  },
  {
    name: 'A preternatural good-striker',
    caskNumber: '112.74',
    price: '120',
    flavourProfile: 'Spicy & sweet',
    age: '12',
    date: 'August 2007',
    region: 'Highland Southern',
    caskType: 'First-fill Moselle oak hogshead',
    abv: '56.8',
    bottleOutturn: '361',
    allocation: '72',
    description: "The nose neat was other-worldly - heavily toasted orange peel and coconut with a little honey, burnt malt loaf with raisins. On the palate brimming with dark cherry sweetness and an oily peppery spiciness that brought to mind a member of the Celtic deity, Sucellus (‘the good striker’), that powerful god of agriculture, forests and wine. Careful when adding water, the aroma was now like an exotic/preternatural Tonka bean and hazelnut crème brûlée, while the taste maintained the theme with that magical Indian dessert Rasgulla which is offered at the Puri Jagannath temple. After nine years in an ex-bourbon hogshead, we transferred this whisky into a 1st fill Moselle oak hogshead."
  },
  {
    name: 'Transcending realms',
    caskNumber: '9.187',
    price: '160',
    flavourProfile: 'Sweet, fruity & mellow',
    age: '16',
    date: 'September 2003',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '53.3',
    bottleOutturn: '224',
    allocation: '90',
    description: "Soft fruits swirled around dried banana, mango and dragon fruit as a little limey zing summoned peppermint, cloves and cardamom pods. Flavours transcended the conscious realms as heather blossom and agave syrup joined fragrant Indian spices over charred pineapple and mango coulis. Water brought us to a place of inner content with an abundance of juicy fruit, marshmallows and lemon meringue pie. Vanilla slices joined soft buttery notes and strawberry milkshake as ripe melon brought a sense of mellow around perfumed sandalwood, cinnamon and toffee. Divine flavours of honey and fudge lasted well onto the finish as this gentle nature demanded careful use of water."
  },
  {
    name: 'Seductive sweetness',
    caskNumber: '24.145',
    price: '405',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '18',
    date: 'March 2002',
    region: 'Speyside Spey',
    caskType: 'First-fill barrel',
    abv: '57.8',
    bottleOutturn: '207',
    allocation: '60',
    description: "The nose gave us a cornucopia of fruits – stewed apples, sultanas, cantaloupe and orange. Mellifluous sweetness – honey, marzipan, treacle tart and deeper aromas of cinnamon, star anise and vanilla. The palate offered a balanced duality of full-on seductive sweetness; spun sugar, butterscotch, marrons glacés, Nutella, baked bananas and more platonic teasing hints of wood spice, mahogany, aftershave and tobacco – definitely complex. The reduced nose discovered beeswax furniture polish, pralines, foamy shrimps and raspberry sauce on ice-cream. The palate became somehow even more complex and more interesting – brown sugar, baklava and fruit syrup; then sweet oak, old leather and warming spices."
  },
  {
    name: 'Abundant treats',
    caskNumber: '35.278',
    price: '280',
    flavourProfile: 'Light & delicate',
    age: '24',
    date: 'October 1995',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '55.1',
    bottleOutturn: '174',
    allocation: '66',
    description: "Abundant sweetness coupled prickly fruit and pear compote with vanilla essence and the evocative aromas of soft leather. Flavours on the tongue combined the dry fruitiness of fresh pomegranate with mixed summer fruits as gentle cinnamon spice encouraged nuances of Madeira cake and maple syrup to come forth. A softer character emerged with water as raspberry jam-filled sponge cake complemented orange peel and floral notes of blossoming lilac. A spicy woodiness surrounded the palate that framed fresh papaya on waffles and dry straw in summer meadows before we finished with the dry tannins of tree bark and white grapes."
  },
  {
    name: "Fragrance and flowers",
    caskNumber: '18.31',
    price: '125',
    flavourProfile: 'Spicy & sweet',
    age: '13',
    date: 'September 2007',
    region: 'Speyside Spey',
    caskType: 'First-fill Rye hogshead',
    abv: '55.9',
    bottleOutturn: '262',
    allocation: '78',
    description: "Buttery biscuits and custard tarts arrived with an impressive amount of fruit that combined mangos, banana chips and satsumas with fragrant honeysuckle and waxy textures. On the palate, a burst of red apples, poached pears and soft plums joined crumbly shortbread sprinkled with ginger, dry roasted almonds and just a suggestion of cocoa powder. With a small dash of water came coconut milk with the accentuated fragrance of cherry blossom, jasmine and buttercups in the sunshine. Fruity flavours now embraced bramble and apricot jam on Battenberg cake with vanilla icing. Orange peel brought a fresh zing as cinnamon spice joined bananas flambeed in spiced rum. After spending 11 years in an ex-bourbon hogshead this was transferred into a 1st fill ex-rye hogshead for the remainder of its maturation."
  },
  {
    name: 'Wood smoke through a porthole',
    caskNumber: '42.52',
    price: '140',
    flavourProfile: 'Peated',
    age: '13',
    date: 'March 2007',
    region: 'Highland Island',
    caskType: 'Refill hogshead',
    abv: '58.3',
    bottleOutturn: '275',
    allocation: '90',
    description: "A fresh sea breeze blew over crumbling chalk cliffs and onto barnacles on fishing boats before whipping up clouds of coal dust and icing sugar that coated lemon meringue pie topped with bacon. Herbal flavours took a medicinal influence with a sweet, barbecued stickiness like an old grill tray as fruit kebabs and chestnuts toasted in applewood smoke. A saltier temperament emerged with water, now with brine, sea air and crab meat dressed in fresh herbs. Coal dust remained on the palate but now at the harbour with lobster pots and smoked salmon. A lovely sweetness complemented smoked ham like honey on pork chops before we finished with a haggis on the loose in a pine forest."
  },
  {
    name: 'Workstation expectation',
    caskNumber: '82.30',
    price: '110',
    flavourProfile: 'Young & spritely',
    age: '9',
    date: 'March 2011',
    region: 'Highland Eastern',
    caskType: 'Second-fill barrel',
    abv: '82.30',
    bottleOutturn: '213',
    allocation: '90',
    description: "The nose, we agreed, had plenty of fruit (banana candies, Maraschino cherries, plums, pears, raspberry jam and white grapes), some dairy notes (buttered bread, whipped cream) and some mint (humbugs, mint choc chip ice-cream) – less unanimously, some of us also found brown sugar, bubblegum, vanilla sponge and sanded oak. The palate delivered sweet fruit liqueurs, cherry, raspberry, grenadine and mint – we imagined a mixologist’s work station; then we identified some pastry and biscuity notes (Empire biscuits) and oaked Chardonnay. The palate also had impressive, mouth-flooding heat (more a comforting warmth in reduction) – with flavours of chilli, gingerbread, Fisherman’s Friends, cumin and mace."
  },
  {
    name: 'Giggle jiggle',
    caskNumber: '7.255',
    price: '160',
    flavourProfile: 'Juicy, oak & vanilla',
    age: '16',
    date: 'November 2003',
    region: 'Speyside Lossie',
    caskType: 'First-fill barrel',
    abv: '56.8',
    bottleOutturn: '209',
    allocation: '90',
    description: "We found this one immediately classical and enticing with everything you'd expect from this great make: white fruit jams, stone fruits, lychee, kumquat, melon, papaya and Juicy Fruit chewing gum. A punchy scent of cask char, honeycomb and star anise evolving towards waxes and light medicines. Reduction brought dried heather, cereals, sunflower oils, pollens, starchy linen and earthy potting sheds. The palate showed an immediate and nourishing spiciness. Then madeira cake, mineral oil, sweet waxiness and heather honey. Reduction ushered the fruits back in and gave us fruit salad juices, ripe mango, pineapple syrup and exotic fruit chutneys. A wee pink wafer biscuit to send us on our way."
  },
  {
    name: 'Classical and fulsome',
    caskNumber: '28.51',
    price: '100',
    flavourProfile: 'Spicy & sweet',
    age: '8',
    date: 'May 2012',
    region: 'Highland Southern',
    caskType: 'First-fill barrel',
    abv: '61.5',
    bottleOutturn: '220',
    allocation: '72',
    description: "A very classical and fulsome aroma greeted the Panel. Honey, vanilla caramel wafers, sugary brandy and liquorice to begin. Then some jumpers full of mothballs, mown grass, pear juice and nectar. Vibrant and vigorous. Reduction brought hints of dried spices from the cupboard, Madagascan vanilla, brown sugar, lemon curd and school pencil case shavings. The palate opened with a lovely syrupy sweetness. Then bags of banana chips, foam banana sweets, doughnuts, cinnamon buns, pear drops, cloves and gooseberry jam. Water made things more zesty, citric and effervescent. Some rye spice, glace cherry syrup and fruit salad gunge."
  },
  {
    name: 'A classic accent',
    caskNumber: '2.122',
    price: '155',
    flavourProfile: 'Deep, rich & dried fruits',
    age: '13',
    date: 'March 2007',
    region: 'Speyside Spey',
    caskType: 'First-fill Oloroso butt',
    abv: '56.4',
    bottleOutturn: '598',
    allocation: '90',
    description: "A clear and classic sherry accent! Bags of date loaf, pure butterscotch, salted caramel popcorn, Toffee Crisp, rosewater, orange marmalade and quince. Also, milk chocolate, figs in syrup, sweet, cured ham and toasted almonds. A tiny kiss of woodsmoke in the background. Water brings lighter and earthier tones of pollen, bitter chocolate, gingerbread, heather honey, Battenberg cake and aged mead. The mouth opens with a lean, slightly meaty and nicely dry sherry but evolves swiftly towards ginger cake, malt loaf, pomegranate syrup, chopped dates and black tea with sugar. With water we got game meat salamis, bouillon stocks and things like treacle sponge, venison ramen, Scotch broth and herbal cough syrups. Dark, deep and intriguing stuff!"
  },
  {
    name: 'War and peat',
    caskNumber: '10.211',
    price: '125',
    flavourProfile: 'Heavily peated',
    age: '7',
    date: 'October 2013',
    region: 'Islay',
    caskType: 'Second-fill Oloroso hogshead',
    abv: '59.9',
    bottleOutturn: '269',
    allocation: '90',
    description: '“Ooft!” said the Panel collectively via Zoom. A bonfire of charred nutmeg, rice pudding doused in petrol and hessian cloth singed at the edges. Then mussels pickled in brine, salt and vinegar crisps, pickled onions, lobster bisque with paprika and baking soda spooned into a rubber hot water bottle full of kerosine. Water brought vinegar-doused gravadlax, a dirty martini full of olive gunge served in a fishing welly, aniseed distillate, smoked chipotle chilli and industrial antiseptic. The mouth opens with a sting of wasabi then hyper-potent, raw peat smoke. Gelatinous in texture, like peated bacon lardons liquefying on your tongue. Pure buckets of tar and anchovy paste rubbed into sheep wool and topped with petroleum jelly. Water adds squid ink, rough and ready ointments, burning creel nets, Germolene and ramen broth mixed with seawater. Matured for five years in a bourbon hogshead before being transferred to a second fill ex-oloroso hogshead.'
  },
  {
    name: 'With a little help from our friends',
    caskNumber: '39.207',
    price: '110',
    flavourProfile: 'Sweet. fruity & mellow',
    age: '9',
    date: 'February 2011',
    region: 'Speyside Lossie',
    caskType: 'Second-fill IPA barrel',
    abv: '61.0',
    bottleOutturn: '251',
    allocation: '60',
    description: "The nose opened with ginger cake, cinnamon sticks in a herbal infusion, blood orange and Jelly Tots. Some pineapple syrup, white stone fruits, pomegranate sorbet and trampled white flowers. Water brought out some gentle notes of coffee, freshly cut daffodils, lemon peelings and white balsamic. The palate showed a slight fizziness, Sherbet Fountain, lots of tinned fruit salad syrups, Juicy Fruit chewing gum and passionfruit sours. With water it became more sweetly cereal and full of pollens, glazed vanilla pastries, custard doughnuts and lemon barley water. Matured for eight years in a bourbon barrel before being transferred to a second fill ex-Tempest Old Fashioned IPA barrel."
  },
  {
    name: 'A delicious and moreish proposition',
    caskNumber: '53.342',
    price: '145',
    flavourProfile: 'Lightly peated',
    age: '11',
    date: 'September 2008',
    region: 'Islay',
    caskType: 'Refill hogshead',
    abv: '59.7',
    bottleOutturn: '265',
    allocation: '90',
    description: "A lovely tingling, sweet peat smoke tantalised our nostrils, while ash, soot and the scent of refreshing lemon eucalyptus essential oil made this an intriguing experience on the nose neat. On the palate there was plenty of sweet peat at first, followed by Dutch beehives (honey-sweetened liquorice) and buttered toffee as well as burnt toast. With a little water it turned towards the maritime and medicinal side on the nose, while the taste became very ambrosial with hints of peat and freshly roasted 100% Colombian arabica beans flavoured with French vanilla – all in all a very delicious and moreish proposition."
  },
  {
    name: 'Dining by the harbour',
    caskNumber: '4.264',
    price: '140',
    flavourProfile: 'Oily & coastal',
    age: '12',
    date: 'January 2008',
    region: 'Highland Island',
    caskType: 'First-fill barrel',
    abv: '61.4',
    bottleOutturn: '254',
    allocation: '90',
    description: "We cooked rainbow trout with lemony caper butter on the beach over a peat fire while we nibbled on slices of toasted coconut bread spread with a creamy pineapple jam made from singed cloves, thyme and sage.  Water added more of the lemon juice and salt with barbequed pineapple slices drizzled with smoked Scottish seaweed. On the palate we were served gambas a la plancha – Spanish style grilled shrimp tapas, whole unpeeled shrimps salted then cooked quickly with lemon juice – pure, simply delicious! At nine years of age, we combined selected hogsheads from the same distillery into a variety of different casks to marry. This is one of those casks"
  },
  {
    name: 'A quick burst',
    caskNumber: '122.35',
    price: '90',
    flavourProfile: 'Spicy & sweet',
    age: '8',
    date: 'May 2012',
    region: 'Highland Southern',
    caskType: 'Second-fill barrel',
    abv: '58.8',
    bottleOutturn: '231',
    allocation: '84',
    description: "A juicy burst of toasted pineapple, squished lemons and orange peel gave an uplifting zip on the nose that sweetened as pink marshmallows joined vanilla pods in banana bread. The fruity sweetness followed onto the palate with an effervescent energy that became balanced by a touch of bitter grape skin and a pinch of spice. With water the citrusy fruits had become lemon meringue pie with white chocolate and a drizzle of caramel. Apples and oranges joined dried papaya while on the palate we found ginger and cinnamon on white icing with a touch of marzipan and tart plums before herbal tea appeared on the finish."
  },
];