enum entitiesActionsTypes {
  SET_ENTITIES = "SET_ENTITIES",
  SET_ACTIVE_ENTITY = "SET_ACTIVE_ENTITY",
  ADD_ENTITY = "ADD_ENTITY",
  UPDATE_ENTITY = "UPDATE_ENTITY",
  DELETE_ENTITY = "DELETE_ENTITY",
  RESET_ENTITIES = "RESET_ENTITIES",
  RESET_ACTIVE_ENTITY = "RESET_ACTIVE_ENTITY"
};

export default entitiesActionsTypes;
