const DESCRIPTIONS = [
  "A velvety blend of dark chocolate and ripe figs, with hints of black cherry and cedarwood, leading to a lingering finish of vanilla and warm spices.",
  "Toasted hazelnuts and charred oak mingle with baking spices and dried apricot, creating a robust yet harmonious profile with a smooth, lasting impression.",
  "Fresh pine and citrus zest are complemented by wildflower honey and sea salt, offering a refreshing and elegant drinking experience.",
  "Orchard fruits and creamy vanilla custard are balanced by cinnamon and toasted almonds, culminating in a symphony of flavors that ends smoothly.",
  "Bold espresso and dark cocoa intertwine with smoky cedar and black pepper, delivering a rich and indulgent palate with a velvety smooth finish.",
  "Ripe peach and honeyed barley are accented by ginger, clove, and a hint of toasted oak, crafting a luxurious and balanced drinking experience.",
  "Sun-drenched oranges and floral heather meet toasted coconut and a hint of campfire smoke, unfolding a serene complexity with every sip.",
  "Aromatic spices and dried fruits intertwine with butterscotch and sea salt, leading to a smooth and satisfying finish with a touch of almond.",
  "Rich toffee and molasses are layered with dark cherries and leather, creating a velvety mouthfeel and a lingering essence of dark chocolate.",
  "Crisp green apple and fresh-cut grass lead into sweet vanilla bean and candied ginger, finishing with a subtle hint of almond and mint.",
  "Dark chocolate and ripe figs meld with black cherry and cedarwood, leaving a lingering impression of vanilla and warm spices.",
  "Toasted hazelnuts and charred oak mingle with baking spices and dried apricot, creating a robust yet harmonious profile with a smooth, lasting finish.",
  "Fresh pine and citrus zest are complemented by wildflower honey and sea salt, offering a refreshing and elegant drinking experience.",
  "Orchard fruits and creamy vanilla custard are balanced by cinnamon and toasted almonds, culminating in a symphony of flavors that ends smoothly.",
  "Bold espresso and dark cocoa intertwine with smoky cedar and black pepper, delivering a rich and indulgent palate with a velvety smooth finish.",
  "Ripe peach and honeyed barley are accented by ginger, clove, and a hint of toasted oak, crafting a luxurious and balanced drinking experience.",
  "Sun-drenched oranges and floral heather meet toasted coconut and a hint of campfire smoke, unfolding a serene complexity with every sip.",
  "Aromatic spices and dried fruits intertwine with butterscotch and sea salt, leading to a smooth and satisfying finish with a touch of almond.",
  "Rich toffee and molasses are layered with dark cherries and leather, creating a velvety mouthfeel and a lingering essence of dark chocolate.",
  "Crisp green apple and fresh-cut grass lead into sweet vanilla bean and candied ginger, finishing with a subtle hint of almond and mint.",
  "Decadent dark chocolate and caramelized figs intertwine with clove and toasted hazelnut, leaving a lasting impression of espresso and spice.",
  "Honeyed cereal and ripe apricot are balanced by ginger and toasted coconut, offering a smooth, velvety finish with hints of oak.",
  "Black cherry and candied orange peel are complemented by cinnamon and toasted oak, creating a velvety texture and a warm, lingering finish.",
  "Meyer lemon and green apple lead into sea spray and toasted almond, with a crisp texture and a refreshing finish of vanilla and floral notes.",
  "Orchid blossoms and honeyed pear meet vanilla bean and cinnamon spice, crafting a silky-smooth drinking experience with a delicate, lingering sweetness.",
  "Toffee and dark chocolate blend with roasted chestnuts and allspice, creating a robust palate and a velvety smooth finish of espresso and oak.",
  "Blackberry and velvety caramel are accented by lavender and smoked sea salt, unfolding a complex profile with a lingering hint of dark caramel.",
  "Ripe peach and honeyed barley mingle with ginger and clove, leading to a luxurious mouthfeel and a finish of butterscotch and sea salt.",
  "Golden honey and toasted almond are complemented by cardamom and dried apricot, offering a plush texture and a satisfying finish with hints of oak.",
  "Fresh citrus and wildflower honey lead into toasted almond and sea salt, creating a smooth, elegant finish with a touch of ginger spice.",
  "Dark chocolate and ripe figs mingle with black cherry and cedarwood, finishing with notes of vanilla and warm spices.",
  "Toasted hazelnuts and charred oak blend with baking spices and dried apricot, providing a harmonious profile and a smooth, lasting finish.",
  "Fresh pine and citrus zest are balanced by wildflower honey and sea salt, offering an elegant, refreshing drinking experience.",
  "Orchard fruits and creamy vanilla custard are enhanced by cinnamon and toasted almonds, culminating in a symphony of flavors with a smooth finish.",
  "Bold espresso and dark cocoa merge with smoky cedar and black pepper, delivering a rich, indulgent palate with a velvety smooth finish.",
  "Ripe peach and honeyed barley are infused with ginger, clove, and toasted oak, resulting in a luxurious, balanced drinking experience.",
  "Sun-drenched oranges and floral heather combine with toasted coconut and campfire smoke, unfolding a serene complexity with each sip.",
  "Aromatic spices and dried fruits meld with butterscotch and sea salt, leading to a satisfying finish that lingers with a touch of almond.",
  "Rich toffee and molasses are layered with dark cherries and leather, creating a velvety mouthfeel and a lingering essence of dark chocolate.",
  "Crisp green apple and fresh-cut grass lead into sweet vanilla bean and candied ginger, finishing with a subtle hint of almond and mint.",
  "Dark chocolate and ripe figs mingle with black cherry and cedarwood, finishing with notes of vanilla and warm spices.",
  "Toasted hazelnuts and charred oak blend with baking spices and dried apricot, providing a harmonious profile and a smooth, lasting finish.",
  "Fresh pine and citrus zest are balanced by wildflower honey and sea salt, offering an elegant, refreshing drinking experience.",
  "Orchard fruits and creamy vanilla custard are enhanced by cinnamon and toasted almonds, culminating in a symphony of flavors with a smooth finish.",
  "Bold espresso and dark cocoa merge with smoky cedar and black pepper, delivering a rich, indulgent palate with a velvety smooth finish.",
  "Ripe peach and honeyed barley are infused with ginger, clove, and toasted oak, resulting in a luxurious, balanced drinking experience.",
  "Sun-drenched oranges and floral heather combine with toasted coconut and campfire smoke, unfolding a serene complexity with each sip.",
  "Aromatic spices and dried fruits meld with butterscotch and sea salt, leading to a satisfying finish that lingers with a touch of almond.",
  "Rich toffee and molasses are layered with dark cherries and leather, creating a velvety mouthfeel and a lingering essence of dark chocolate.",
  "Crisp green apple and fresh-cut grass lead into sweet vanilla bean and candied ginger, finishing with a subtle hint of almond and mint.",
];

export default DESCRIPTIONS;
